//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeJsExport.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThreeJsExport.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API.
        /// </summary>
        internal static string ApiGrooveGroupText {
            get {
                return ResourceManager.GetString("ApiGrooveGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on a circular edge to create an API Groove..
        /// </summary>
        internal static string ApiGrooveStatusText {
            get {
                return ResourceManager.GetString("ApiGrooveStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an API groove of a desired size..
        /// </summary>
        internal static string ApiGrooveToolHint {
            get {
                return ResourceManager.GetString("ApiGrooveToolHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ring Groove.
        /// </summary>
        internal static string ApiGrooveToolText {
            get {
                return ResourceManager.GetString("ApiGrooveToolText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribute.
        /// </summary>
        internal static string DistributeGroupText {
            get {
                return ResourceManager.GetString("DistributeGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribute spheres across a body using a physics-based partical model..
        /// </summary>
        internal static string DistributeSpheresCommandHint {
            get {
                return ResourceManager.GetString("DistributeSpheresCommandHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spheres.
        /// </summary>
        internal static string DistributeSpheresCommandText {
            get {
                return ResourceManager.GetString("DistributeSpheresCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string DistributeSpheresToolAnimationPause {
            get {
                return ResourceManager.GetString("DistributeSpheresToolAnimationPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string DistributeSpheresToolAnimationPlay {
            get {
                return ResourceManager.GetString("DistributeSpheresToolAnimationPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step.
        /// </summary>
        internal static string DistributeSpheresToolAnimationStep {
            get {
                return ResourceManager.GetString("DistributeSpheresToolAnimationStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evenly distribute spheres on a face..
        /// </summary>
        internal static string DistributeSpheresToolHint {
            get {
                return ResourceManager.GetString("DistributeSpheresToolHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space Spheres.
        /// </summary>
        internal static string DistributeSpheresToolText {
            get {
                return ResourceManager.GetString("DistributeSpheresToolText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;customUI&gt;
        ///    &lt;ribbon&gt;
        ///        &lt;tabs&gt;
        ///            &lt;tab label=&quot;ThreeJsExport&quot; id=&quot;ThreeJsExport&quot;&gt;
        ///                &lt;group label=&quot;ThreeJsExport.Three.js&quot; layoutOrientation=&quot;horizontal&quot; itemSpacing=&quot;&quot; id=&quot;ThreeJsExportGroup&quot;&gt;
        ///                    &lt;button size=&quot;large&quot; id=&quot;ThreeJsExportButton&quot; command=&quot;ThreeJsExport&quot;/&gt;
        ///        &lt;/group&gt;
        ///      &lt;/tab&gt;
        ///    &lt;/tabs&gt;
        ///  &lt;/ribbon&gt;
        ///&lt;/customUI&gt;.
        /// </summary>
        internal static string Ribbon {
            get {
                return ResourceManager.GetString("Ribbon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle.
        /// </summary>
        internal static string ThreadAngle {
            get {
                return ResourceManager.GetString("ThreadAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal.
        /// </summary>
        internal static string ThreadIsInternal {
            get {
                return ResourceManager.GetString("ThreadIsInternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pitch.
        /// </summary>
        internal static string ThreadPitch {
            get {
                return ResourceManager.GetString("ThreadPitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string ThreadPosition {
            get {
                return ResourceManager.GetString("ThreadPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        internal static string ThreadPositionCenter {
            get {
                return ResourceManager.GetString("ThreadPositionCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inside.
        /// </summary>
        internal static string ThreadPositionInside {
            get {
                return ResourceManager.GetString("ThreadPositionInside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outside.
        /// </summary>
        internal static string ThreadPositionOutside {
            get {
                return ResourceManager.GetString("ThreadPositionOutside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threads.
        /// </summary>
        internal static string ThreadsGroupText {
            get {
                return ResourceManager.GetString("ThreadsGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Millimeters per thread.
        /// </summary>
        internal static string ThreadSpecificationMillimetersPerThread {
            get {
                return ResourceManager.GetString("ThreadSpecificationMillimetersPerThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threads per inch.
        /// </summary>
        internal static string ThreadSpecificationThreadsPerInch {
            get {
                return ResourceManager.GetString("ThreadSpecificationThreadsPerInch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread.
        /// </summary>
        internal static string ThreadStructureText {
            get {
                return ResourceManager.GetString("ThreadStructureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create threads on selected cylinder..
        /// </summary>
        internal static string ThreadToolCommandHint {
            get {
                return ResourceManager.GetString("ThreadToolCommandHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string ThreadToolCommandText {
            get {
                return ResourceManager.GetString("ThreadToolCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a threaded body based on the size of the selected cylinder..
        /// </summary>
        internal static string ThreadToolStatusText {
            get {
                return ResourceManager.GetString("ThreadToolStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three.js.
        /// </summary>
        internal static string ThreeJsText {
            get {
                return ResourceManager.GetString("ThreeJsText", resourceCulture);
            }
        }
    }
}
